"""initial estate monitor schema

Revision ID: 041abf232353
Revises: c9b8c3aa1b92
Create Date: 2026-03-14 19:47:55.615287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '041abf232353'
down_revision: Union[str, Sequence[str], None] = 'c9b8c3aa1b92'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('risk_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tenants', 'risk_score')
    # ### end Alembic commands ###
