"""add rent_due_date

Revision ID: 587258fd3c9c
Revises: b6b70c87cfde
Create Date: 2026-03-20 05:32:38.688462

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '587258fd3c9c'
down_revision: Union[str, Sequence[str], None] = 'b6b70c87cfde'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tenants', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=False)
    op.drop_index(op.f('phone'), table_name='tenants')
    op.create_unique_constraint(None, 'tenants', ['phone_number'])
    op.drop_column('tenants', 'phone')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('phone', mysql.VARCHAR(length=20), nullable=False))
    op.drop_constraint(None, 'tenants', type_='unique')
    op.create_index(op.f('phone'), 'tenants', ['phone'], unique=True)
    op.alter_column('tenants', 'phone_number',
               existing_type=mysql.VARCHAR(length=20),
               nullable=True)
    # ### end Alembic commands ###
