"""add page_blocks table

Revision ID: 65b4e4efa4a8
Revises: 169d524f07dd
Create Date: 2026-03-20 05:31:58.275488

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '65b4e4efa4a8'
down_revision: Union[str, Sequence[str], None] = '169d524f07dd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('page_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('section', sa.String(length=50), nullable=True),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('subtitle', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('button_text', sa.String(length=100), nullable=True),
    sa.Column('button_link', sa.String(length=200), nullable=True),
    sa.Column('position', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_page_blocks_id'), 'page_blocks', ['id'], unique=False)
    op.drop_index(op.f('ix_property_sales_id'), table_name='property_sales')
    op.drop_table('property_sales')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('property_sales',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('property_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('property_address', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('price', mysql.FLOAT(), nullable=False),
    sa.Column('seller_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('buyer_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.ForeignKeyConstraint(['buyer_id'], ['users.id'], name=op.f('property_sales_ibfk_2')),
    sa.ForeignKeyConstraint(['seller_id'], ['users.id'], name=op.f('property_sales_ibfk_1')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_property_sales_id'), 'property_sales', ['id'], unique=False)
    op.drop_index(op.f('ix_page_blocks_id'), table_name='page_blocks')
    op.drop_table('page_blocks')
    # ### end Alembic commands ###
