"""Add soft-delete and is_admin to users

Revision ID: 8025aaafa2be
Revises: 041abf232353
Create Date: 2026-03-17 20:57:17.252017

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8025aaafa2be'
down_revision: Union[str, Sequence[str], None] = '041abf232353'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('company_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'tenants', 'companies', ['company_id'], ['id'])
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'deleted_at')
    op.drop_column('users', 'is_deleted')
    op.drop_column('users', 'is_admin')
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.drop_column('tenants', 'company_id')
    # ### end Alembic commands ###
