"""Add gateway and reference to rent_payments

Revision ID: c9b8c3aa1b92
Revises: 110826b43fd4
Create Date: 2026-03-13 10:50:39.848433

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'c9b8c3aa1b92'
down_revision: Union[str, Sequence[str], None] = '110826b43fd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('app_name', sa.String(length=150), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('primary_color', sa.String(length=50), nullable=True),
    sa.Column('whatsapp_number', sa.String(length=50), nullable=True),
    sa.Column('facebook_page', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('carousel_ads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('image_url', sa.String(length=500), nullable=False),
    sa.Column('headline', sa.String(length=255), nullable=True),
    sa.Column('sub_text', sa.String(length=255), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('corporate_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=150), nullable=True),
    sa.Column('contact_email', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('audits',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audits_id'), 'audits', ['id'], unique=False)
    op.create_index(op.f('ix_audits_user_id'), 'audits', ['user_id'], unique=False)
    op.create_table('recommendation_blocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('link_url', sa.String(length=500), nullable=True),
    sa.Column('position', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_user_comments_id'), table_name='user_comments')
    op.drop_table('user_comments')
    op.add_column('rent_payments', sa.Column('gateway', sa.String(length=50), nullable=False))
    op.add_column('rent_payments', sa.Column('reference', sa.String(length=100), nullable=False))
    op.create_unique_constraint(None, 'rent_payments', ['reference'])
    op.add_column('tenants', sa.Column('full_name', sa.String(length=255), nullable=False))
    op.add_column('tenants', sa.Column('property_id', sa.Integer(), nullable=True))
    op.alter_column('tenants', 'phone',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=20),
               nullable=False)
    op.drop_index(op.f('email'), table_name='tenants')
    op.create_unique_constraint(None, 'tenants', ['phone'])
    op.drop_constraint(op.f('tenants_ibfk_1'), 'tenants', type_='foreignkey')
    op.create_foreign_key(None, 'tenants', 'properties', ['property_id'], ['id'])
    op.drop_column('tenants', 'email')
    op.drop_column('tenants', 'last_name')
    op.drop_column('tenants', 'password')
    op.drop_column('tenants', 'company_id')
    op.drop_column('tenants', 'is_active')
    op.drop_column('tenants', 'first_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tenants', sa.Column('first_name', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('tenants', sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('tenants', sa.Column('password', mysql.VARCHAR(length=255), nullable=False))
    op.add_column('tenants', sa.Column('last_name', mysql.VARCHAR(length=150), nullable=False))
    op.add_column('tenants', sa.Column('email', mysql.VARCHAR(length=255), nullable=False))
    op.drop_constraint(None, 'tenants', type_='foreignkey')
    op.create_foreign_key(op.f('tenants_ibfk_1'), 'tenants', 'companies', ['company_id'], ['id'])
    op.drop_constraint(None, 'tenants', type_='unique')
    op.create_index(op.f('email'), 'tenants', ['email'], unique=True)
    op.alter_column('tenants', 'phone',
               existing_type=sa.String(length=20),
               type_=mysql.VARCHAR(length=50),
               nullable=True)
    op.drop_column('tenants', 'property_id')
    op.drop_column('tenants', 'full_name')
    op.drop_constraint(None, 'rent_payments', type_='unique')
    op.drop_column('rent_payments', 'reference')
    op.drop_column('rent_payments', 'gateway')
    op.create_table('user_comments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('comment', mysql.TEXT(), nullable=False),
    sa.Column('created_by', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('visibility', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('is_internal', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('user_comments_ibfk_1')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_comments_ibfk_2')),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_user_comments_id'), 'user_comments', ['id'], unique=False)
    op.create_table('payments',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('amount', mysql.FLOAT(), nullable=False),
    sa.Column('payment_method', mysql.VARCHAR(length=50), nullable=False),
    sa.Column('status', mysql.VARCHAR(length=20), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('current_timestamp()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='latin1_swedish_ci',
    mysql_default_charset='latin1',
    mysql_engine='InnoDB'
    )
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.drop_table('recommendation_blocks')
    op.drop_index(op.f('ix_audits_user_id'), table_name='audits')
    op.drop_index(op.f('ix_audits_id'), table_name='audits')
    op.drop_table('audits')
    op.drop_table('corporate_accounts')
    op.drop_table('carousel_ads')
    op.drop_table('audit_logs')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
